[package]
name = "mail-indicator"
version = "0.1.0"
authors = ["fpalacios <fedenator7@gmail.com>"]
edition = "2018"

[dependencies]
libappindicator = "0.4.0"
gtk             = "0.4.0"
glib            = "0.5.0"
imap            = "1.0.2"
native-tls      = "0.2"
oauth2          = "1.3.0"
# oauth2          = { git = "https://github.com/ramosbugs/oauth2-rs", tag = "3.0.0-alpha.3" }
